mainprefix: "+"// you change your bot prefix here 
defaultjoinmessage: "**{user} Joined Invited By {Inviter} (Invites: {inv})**"
defaultleavemessage: "**{user} Left, Invited by {inviter}**"
token: "bot-token" // put your bot token here
color: "BLUE"
